# Generated by Django 3.0 on 2021-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mycart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mycart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
